### ISSUE TITLE
In recipes list view if the page is refreshed the list of recipes dissapears

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#118]
There are several recipes in recipes list view, if you refresh the page, it dissapear, you have to go for example to home tab and then to recipes tab again so the list is shown again.
Having the app open via: https://fxbox.github.io/app

**Comment by azasypkin** [comment]
Hey @isabelrios do you still see this issue on the latest master?

I believe I've fixed this in https://github.com/fxbox/app/pull/120

**Comment by isabelrios** [comment]
Hi @azasypkin it does not reproduce now!good!
Definetely not the same problem and maybe not to fix now but after refresing the list dissapears for a few seconds and then it appears, so there is sometime in between where the list of recipes does not show anything. Do you want me to open another enhacenment issue for that?

Thanks!

**Comment by azasypkin** [comment]
Thanks for confirming!

> Definetely not the same problem and maybe not to fix now but after refresing the list dissapears for a few seconds and then it appears, so there is sometime in between where the list of recipes does not show anything. Do you want me to open another enhancement issue for that?

Yes, please file another UI issue about some sort of progress bar or indicator that will let user know that we're connecting to the box and fetching data.

**Comment by isabelrios** [comment]
Sure! 

So closing this one! Thanks!
