### ISSUE TITLE
Cannot open the app from Chrome beta on android

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#119]
This was working for me before. Now I get the log in page, but it is like it does not detect the foxbox since the Connect to foxbox button never gets active...
Will try with other devices...

**Comment by gmarty** [comment]
Yes, we have a serious regression on the login page that I'm fixing in https://github.com/fxbox/app/pull/127. Hopefully it will land soon.

**Comment by azasypkin** [comment]
> Yes, we have a serious regression on the login page that I'm fixing in #127. Hopefully it will land soon.

Can we close this one now @gmarty ?

**Comment by isabelrios** [comment]
I have tried again, now that #127 has been merged, but still not able to open the app

**Comment by azasypkin** [comment]
@isabelrios I've just managed to successfully open the app [1] on Chrome Beta 51.0.2704.28 on my android device.

If you open app via https, you need to first open [2] in a separate tab and confirm security exception.

Could you please try again with security exception accepted?

[1] https://fxbox.github.io/app
[2] https://knilxof.org:4443

**Comment by isabelrios** [comment]
Hey! @azasypkin yeah, you are right, forgot about adding the exception.
Closing this issue. Thanks!
