### ISSUE TITLE
Settings class must listen to storage event

### ISSUE THREAD

**Issue by gmarty** [fxbox/app#144]
Whenever a local storage value is edited outside of the lib (by a 3rd party script or using the devtools), the state may get out of sync and lead to unpredictable effect.
We should listen to the `storage` event and update the internal value in Settings accordingly. This will allow us to edit some settings in the devtools and can be useful for demos on mobile.

**Comment by azasypkin** [comment]
Please note that ```storage``` event is only fired when storage is changed _outside of current document_ - from iframe, another tab or window. Even though it limits possible use cases it's still beneficial when app is opened in several tabs/window.
