### ISSUE TITLE
Support multiple box

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/app#15]
When the discovery server returns several boxes, the user should be able to select one.

We hit that frequently in the office...

@azasypkin or @gmarty  is that something you can look at this week?

**Comment by azasypkin** [comment]
Hey @gmarty, per yesterday's IRC log I see that you'll likely take a look at it. Let me know if you need a spare hand :)

**Comment by gmarty** [comment]
Closing as per https://github.com/fxbox/app/commit/e8a462751e973358b59e17af5764bae68fdfd167
