### ISSUE TITLE
Polyfill for no IndexedDB support

### ISSUE THREAD

**Issue by gmarty** [fxbox/app#165]
If IndexedDB is not supported by the browser, the app won't work at all. This impacts at least the following situations:
* Firefox in private mode
* iOS in web app (full screen app) mode (and webview probably), see #154

For such environments, we should use a in-memory storage instead of IndexedDB.

**Comment by azasypkin** [comment]
@gmarty can we use `localStorage` instead of in-memory storage or it's also not available?

**Comment by azasypkin** [comment]
Will evaluate how hard it is.

**Comment by gmarty** [comment]
I don't think using localStorage is required. We can just use a in-memory storage that's not persisted on the browser, populate it from the box at startup.
It's good to support browser without IndexedDB but we should not spend too much time getting a on par experience with the ones supporting it.

**Comment by azasypkin** [comment]
We already use localStorage for settings, so my idea was to somehow reuse the same thing in two places. But that's what I'm going to evaluate and choose the simplest and reasonable approach:)
