### ISSUE TITLE
Camera view is broken by incompatible API change

### ISSUE THREAD

**Issue by azasypkin** [fxbox/app#40]
See https://github.com/fxbox/foxbox/pull/290

+ We need to somehow notify about breaking changes in API.

**Comment by azasypkin** [comment]
Fix likely requires changes in Foxbox as well, as data type for newest image has changed from ```Binary``` to ```Unit``` for some reason https://github.com/fxbox/foxbox/pull/290/files#r58179169

**Comment by azasypkin** [comment]
Ugh, new change for binary response is coming (https://github.com/fxbox/foxbox/pull/297), so it makes sense to not fix it right now to avoid double work :/

**Comment by Yoric** [comment]
The change for binary response is still very much a WIP. Don't hold your breath :)
