### ISSUE TITLE
Concatenate and minify the generate scripts

### ISSUE THREAD

**Issue by gmarty** [fxbox/app#45]
When we remove the transpilation to es5 (see #44), we want to concatenate and minify the build.
AFAIK, there's no minifier that support outputting es6 code, so we can use something like https://www.npmjs.com/package/mangle-my-js by @jonathanKingston

**Comment by gmarty** [comment]
We should also use [rollupjs](http://rollupjs.org/guide/#comparison) to bundle the files together.

**Comment by azasypkin** [comment]
Fixed via #163
