### ISSUE TITLE
GET to <foxbox url>:3000/ping instead of <foxbox url>/ping

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#55]
Hello @gmarty, there is one issue we would like to check in order to understand if there is a bug:
Scenario:
Running foxbox in pc1 with: cargo run -- -r http://knilxof.org:4242 -t knilxof.org:443 -s foxbox --remote-name test.knilxof.org --disable-tls
Running foxapp in a pc2 firefox browser:  https://fxbox.github.io/app 
Both in same network.
The list of devices is not retrieved.*

In the network console logs it is possible to see a GET to: test:3000/ping which never gets a 200 response.
Locally running both foxbox and foxapp in same pc is working, could be that fetching the remote url is done correctly but it is failing parsing it?

*Tried foxbox.clear() but then there was this error: Polling has failed, scheduling one more attempt: DOMException[InvalidStateError:"A mutation operation was attempted on a database that did not allow mutations"

**Comment by gmarty** [comment]
You need to refresh the page once you've done `foxbox.clear()`.
Please try again and let me know how it goes.

**Comment by isabelrios** [comment]
This is what I get: I do foxbox.clear() then refresh the page, and I am redirected to the Log in page, I tap on login, see the  Please enter your admin password screen, type my password, then I enter in the home view but still the list (in this case the camera) is not shown.
In console logs there is now an error: Redirecting to an url without session that could be the reason why the list is not shown. But this error is only shown if I refresh, otherwise the problem is the described above.

I am also seeing a SecurityError: The operation is insecure.

**Comment by isabelrios** [comment]
@gmarty Some updates on this...
On desktop firefox (and firefox nightly), chrome (and chrome beta) I still reproduce the reported problem
On Android with chrome beta I can see the app correctly with the camera listed and it works taking a snapshot
On Android with firefox nightly, the camera does not appear

cc fyi @JohanLorenzo, @npark-mozilla

**Comment by isabelrios** [comment]
@gmarty It is still possible to see this ping to a non correct end point, it never receives a response.
Although now the services are retrieved and I can see the camera listed we should understand why the get to that end point and change it to a correct one, what do you think? Thanks!

Scenario:
Running fxobox in pc1
Running https://fxbox.github.io/app in pc2
Both in same network

**Comment by azasypkin** [comment]
Sorry, not sure that I correctly understand the issue here :) @gmarty what should we fix in the scope of this one?

**Comment by npark-mozilla** [comment]
I believe this is no longer reproducing, I'll go ahead and close this issue.

**Comment by azasypkin** [comment]
Thanks!
