### ISSUE TITLE
Integrate CordovaHTTP into app's code

### ISSUE THREAD

**Issue by michielbdejong** [fxbox/app#6]
In #3 I'm adding `window.qr` for debugging; this is a follow-up ticket for integrating this properly into the app's mvc structure.

**Comment by michielbdejong** [comment]
We should use the `getUserMedia`-based code from webqr.com for this (though will need a fallback for iOS which doesn't support `getUserMedia`, see https://public.etherpad-mozilla.org/p/link-connection-solutions#lineNumber=21).

This is parked for now, as decided in https://public.etherpad-mozilla.org/p/link-connection-solutions#lineNumber=18

**Comment by azasypkin** [comment]
Hey @michielbdejong what exactly should be done in the scope of this issue? I've seen you removed some cordova code recently, hence asking.

**Comment by michielbdejong** [comment]
Yes, this can be closed now, sorry.
