### ISSUE TITLE
Not possible to differentiate which light is actually being used and the correct status

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#77]
Here an screenshot of what I have 
<img width="319" alt="captura de pantalla 2016-04-13 a las 15 26 15" src="https://cloud.githubusercontent.com/assets/1897507/14494753/c9c1045a-018c-11e6-8324-d5cb138883d8.png">

@gmarty A few things related to the status of the light services:
I am using only light bulb 2, the other two are not connected, I would expect the other light services to be greyed out or shown in a different way?
Also the checkbox for all of them appears as clicked which is the status for on, and they are off.
And, about the red square, should it change to green when turning on the light?

I added several comments here, since not sure they are actually issues, if they are, I can open separate issues if you prefer. Thanks!

**Comment by npark-mozilla** [comment]
FYI, There is a getter that states whether the lightbulb is present (i.e.: "getter:available.1.001788fffe230b96.philips_hue@link.mozilla.org").

**Comment by gmarty** [comment]
This is also fixed in the latest master. Please check and close if it's working for you.

**Comment by isabelrios** [comment]
This seems to be working fine now on my side.
Lets confirm on @npark-mozilla's  before closing it.
Thanks!!

**Comment by isabelrios** [comment]
This is working also in his side, so now, definetively, closing it :)
