### ISSUE TITLE
Can not log in in the app from a different device, it tries to connect to "undefined:3000/..."

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#78]
With latest changes I am not able to open the app from a different device (android mobile with chrome beta).
https://fxbox.github.io/app opens log in page but upon tapping on log in button the Not possible to connect to this web site is shown

**Comment by ferjm** [comment]
I think https://github.com/fxbox/app/pull/27 will probably fix this.

**Comment by azasypkin** [comment]
> I think #27 will probably fix this.

So can we close this one now @isabelrios @ferjm ?

**Comment by isabelrios** [comment]
I can open the app in another device, have not seen this error lately, so I think we can close it

**Comment by azasypkin** [comment]
Okay, thanks, let's close it then.
