### ISSUE TITLE
UI does not mark hue lightbulbs that are registered to the hub but not present.

### ISSUE THREAD

**Issue by npark-mozilla** [fxbox/app#81]
There is a getter that states whether the lightbulb is present (i.e.: "getter:available.1.001788fffe230b96.philips_hue@link.mozilla.org"). But on the UI App, all found service adapters are set to available.  UI App should filter out the ones that are not present.

**Comment by isabelrios** [comment]
This was also commented in issue [#77](https://github.com/fxbox/app/issues/77)

**Comment by npark-mozilla** [comment]
ah, it's a dupe then. sorry, I'll close it
