### ISSUE TITLE
Status of the light bulb is not kept when loging out

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#82]
Not sure this is also related or caused by [ issue 77] (https://github.com/fxbox/app/issues/77)
Once the app is open, from the home view change the status of a light from on to off. (Due to issue 77 you first have to uncheck the check box and then check it again so the light is on) 
If you log out and then log in with same user, the light status according to the app is on, but it is actually off.

**Comment by gmarty** [comment]
This should be fixed now. Can you please try again?

**Comment by isabelrios** [comment]
Yes, now the status is saved althought you log out. Closing this issue
