### ISSUE TITLE
Cannot take a picture

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#83]
With the same version of foxbox and foxapp I was able to take a picture without problems but it stopped working.

I can see in the console: "_Error occurred while making a snapshot:  _SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data_" when tapping on the button to take a snapshot and the next screen with the view of the picture is not shown.
Although in the foxbox traces I can see that actually the picture was taken:_ [2016-04-14 11:11:14.042] INFO  Took a snapshot from ae67e622-7a66-465e-bab0-b0c5541a6eb4: /Users/irios/.local/share/foxbox/snapshots/ae67e622-7a66-465e-bab0-b0c5541a6eb4/2016-04-14-111114.jpg_

*One thing I have not done before I saw this issue was trying to add a recipe including the camera, but it was not added as per bug issue #68 and also I closed everything and launched both foxbox and foxapp from the scratch.

**Comment by isabelrios** [comment]
This is working again, will try to reproduce again and if not possible will close it.

**Comment by azasypkin** [comment]
Hey @isabelrios so can we close this issue?

**Comment by isabelrios** [comment]
@azasypkin I was not able to reproduce this anymore. Will close it and open in case it is reproduced
