### ISSUE TITLE
Warning when no Box is discovered and app defaults to localhost:3000

### ISSUE THREAD

**Issue by michielbdejong** [fxbox/app#9]
When discovery fails (for instance when the Box did not register its local IP in the last 60 seconds), we silently fall back to using localhost:3000. We could add a warning when this happens (at least a `console.warn` something).

**Comment by michielbdejong** [comment]
Maybe we should even remove this fallback altogether, depending on build config.

**Comment by michielbdejong** [comment]
Also, as noted in https://github.com/fxbox/app/issues/64#issuecomment-208181859, there is no error message first time accessing the app from a different network.

**Comment by ferjm** [comment]
This is really annoying and it's confusing people trying to test the app. We should definitely not default to localhost. Right now you are forced to run things in this order: start foxbox -> browse to app. If you do it the other way around, you are stuck in localhost. With TLS support landing and making localhost unusable, this is specially painful.

**Comment by ferjm** [comment]
#96

**Comment by azasypkin** [comment]
Hey @ferjm, does https://github.com/fxbox/app/pull/96 resolve this issue?

**Comment by ferjm** [comment]
Yes, this was fixed by #96. Thanks!
