### ISSUE TITLE
There is no way to know which light you are adding to a recipe

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#90]
Please see below screenshot:
![captura de pantalla 2016-04-15 a las 12 05 20](https://cloud.githubusercontent.com/assets/1897507/14558372/6f1dad88-0302-11e6-90e2-8020659de474.png)

Should it be expected to have a number or name to differenciate them? or should it be the tag (which btw is not saved if it is selected for a service)?

**Comment by azasypkin** [comment]
>  or should it be the tag (which btw is not saved if it is selected for a service)?

Yep, I think this is a way to go, but it's not implemented yet, I'll see if I can easily do this in https://github.com/fxbox/app/issues/98

**Comment by isabelrios** [comment]
One more comment, since you cannot diferentiate the lights, there is no way to add a recipe for example with same getter but different lights as setters. It thinks it is the same recipe although the lights are different...
